version: "3.9"
services:
  db:
    image: postgres:15-alpine
    container_name: csvkit-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: deploy/Dockerfile.api
    container_name: csvkit-api
    env_file: .env
    environment:
      - ALLOWED_ORIGIN=http://localhost:3000
    ports:
      - "${API_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: deploy/Dockerfile.web
    container_name: csvkit-web
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    depends_on:
      - api

  migrator:
    image: migrate/migrate:4
    volumes:
      - ./db/migrations:/migrations
    # 直結(5432)のURLをこのファイルから読む
    env_file: .env.migrations
    # $ を使わず、エントリポイントを配列で素直に渡す
    entrypoint:
      - migrate
      - -path=/migrations
      - -database
      - ${DATABASE_URL}


volumes:
  dbdata:
