services:
  - type: web
    name: csv-import-kit-api-prod
    runtime: docker          # もしエラーが出る場合は env: docker に変更
    plan: free
    region: singapore
    branch: main
    dockerfilePath: deploy/Dockerfile.api
    healthCheckPath: /readyz
    autoDeploy: true

    envVars:
      - fromGroup: csv-import-kit-prod   # ← 事前に作成した Environment Group 名
